version: '3'

services:
  mysqldb:
    container_name: mysql
    build:
      context: ./docker
      dockerfile: DockerFile
    env_file:
      - docker/env/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./docker/cnf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"